defaultTargets = ["EosScheduling"]
keywords       = ["math"]
name           = "EosScheduling"
version        = "0.1.0"

[leanOptions]
maxSynthPendingDepth           = 3
pp.unicode.fun                 = true  # pretty-prints `fun a ↦ b`
relaxedAutoImplicit            = false
weak.linter.mathlibStandardSet = true

[[require]]
name  = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "EosScheduling"
